#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Initialize Docker cluster environment

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Initializes the Docker cluster environment as follows:

   - Copy cache.xml to the '$GEODE_DOCKER_CLUSTER' docker cluster
   - Create the 'nw' database in MySQL

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

# Copy cache.xml to the geode cluster. It includes co-located data configuration
# for the /nw/orders region. Power BI files are located in etc/powerbi/ for generating
# reports using the co-located data.
echo ""
if [ -d $PADOGRID_WORKSPACE/docker/$GEODE_DOCKER_CLUSTER ]; then
   cp ../padogrid/etc/cache.xml $PADOGRID_WORKSPACE/docker/$GEODE_DOCKER_CLUSTER/padogrid/etc/cache.xml
   echo "Copied cache.xml to the $GEODE_DOCKER_CLUSTER docker cluster."
else
   echo "Failed to copy 'cache.xml' to the '$GEODE_DOCKER_CLUSTER' docker cluster because it does not exist."
   echo "This file configures Geode with co-located data. If want to co-locate data then either"
   echo "create a docker cluster named, '$GEODE_DOCKER_CLUSTER', or copy the provided 'cache.xml' file to"
   echo "your Geode docker cluster as follows:"
   echo ""
   echo "   cp ../padogrid/etc/cache.xml \$PADOGRID_WORKSPACE/docker/<geode_docker_cluster_name>/padogrid/etc/"
echo ""
fi

# Create nw database and grant all permissions to the user debezium
docker exec -e MYSQL_PWD=debezium -it mysql /bin/bash -c \
"mysql -uroot -e \"GRANT ALL PRIVILEGES ON nw.* TO 'debezium'@'%'; CREATE DATABASE IF NOT EXISTS nw;\""
echo "nw database created."
echo ""

