#!/usr/bin/env bash

if [ "$1" == "" ]; then
   echo >&2 "ERROR: Topic is not specified. Command aborted."
   exit 1
fi

docker run --rm --tty --network debezium_cp_default confluentinc/cp-kafkacat kafkacat -b broker:29092 -t $1
